"""add production_consumed and produced custody event types

Revision ID: 137e813427da
Revises: e277bc243b63
Create Date: 2026-09-29 18:13:46.852726
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '137e813427da'
down_revision: str | Sequence[str] | None = 'e277bc243b63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE custodyeventtype ADD VALUE IF NOT EXISTS 'PRODUCTION_CONSUMED'")
    op.execute("ALTER TYPE custodyeventtype ADD VALUE IF NOT EXISTS 'PRODUCED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
