"""add custody_events table

Revision ID: 58b9670718f5
Revises: 9825165bbc89
Create Date: 2026-09-26 19:13:18.653041
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "58b9670718f5"
down_revision: str | Sequence[str] | None = "9825165bbc89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custody_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("RECEIVED", "MOVED", name="custodyeventtype"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("from_location_id", sa.UUID(), nullable=True),
        sa.Column("to_location_id", sa.UUID(), nullable=True),
        sa.Column("production_run_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custody_events_unit_id"), "custody_events", ["unit_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custody_events_unit_id"), table_name="custody_events")
    op.drop_table("custody_events")
    # ### end Alembic commands ###
