"""core inventory model: product, location, lot, unit

Revision ID: 5eec8fb9dbd6
Revises:
Create Date: 2026-09-26 16:28:00.214817
"""

from collections.abc import Sequence

revision: str = "5eec8fb9dbd6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
