"""add production run, input and input unit models

Revision ID: e277bc243b63
Revises: e395b66d6f47
Create Date: 2026-09-29 17:56:45.741624
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e277bc243b63"
down_revision: str | Sequence[str] | None = "e395b66d6f47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("output_lot_id", sa.UUID(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["output_lot_id"],
            ["lots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("output_lot_id"),
    )
    op.create_table(
        "production_inputs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("production_run_id", sa.UUID(), nullable=False),
        sa.Column("input_lot_id", sa.UUID(), nullable=False),
        sa.Column("quantity_consumed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["input_lot_id"],
            ["lots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["production_run_id"],
            ["production_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_inputs_input_lot_id"),
        "production_inputs",
        ["input_lot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_inputs_production_run_id"),
        "production_inputs",
        ["production_run_id"],
        unique=False,
    )
    op.create_table(
        "production_input_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("production_input_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["production_input_id"],
            ["production_inputs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unit_id"),
    )
    op.create_index(
        op.f("ix_production_input_units_production_input_id"),
        "production_input_units",
        ["production_input_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_production_input_units_production_input_id"),
        table_name="production_input_units",
    )
    op.drop_table("production_input_units")
    op.drop_index(
        op.f("ix_production_inputs_production_run_id"), table_name="production_inputs"
    )
    op.drop_index(
        op.f("ix_production_inputs_input_lot_id"), table_name="production_inputs"
    )
    op.drop_table("production_inputs")
    op.drop_table("production_runs")
    # ### end Alembic commands ###
